
dataset:
  data_root_path: 'registrated_ADNI1GO_CrossSectional_Affine_noRAI'
  diag_csv_path: 'DXSUM_PDXCONV_ADNIALL_24Sep2023.csv'
  data_collection_csv_path: 'ANDI1GO_postprocess_10_09_2023.csv'
  clinical_path: 'ADNIMERGE_05Jan2024.csv'
  gene_dir_path: 'ADNI_1_GWAS_Plink/ADNI_cluster_01_forward_757LONI'
  apoe_gene_dir_path: 'PLINK_APOE/extracted_snps'
  pred_xMonth: 2 
  seq_len: 3
  nor_img_flag: True
  seq_aug_flag: False 
  pad_mode: 'NO_PAD' # ZEROS, NO_PAD, REPLICATE
  time_emd_type: 'month'
  TEM_a: 0.5
  TEM_b: 0.5
  data_split_ratio: [0.75,0.05,0.20]
  seed: 32
  data_pct: 1
  is_shuffle: True
  clinical_numerical_features: 
    - 'AGE'
    - 'PTEDUCAT'
    - 'APOE4'
    - 'CDRSB'
    - 'ADAS11'
    - 'ADAS13'
    - 'ADASQ4'
    - 'MMSE'
    - 'RAVLT_immediate'
    - 'RAVLT_learning'
    - 'RAVLT_forgetting'
    - 'RAVLT_perc_forgetting'
    - 'LDELTOTAL'
    - 'DIGITSCOR'
    - 'TRABSCOR'
    - 'FAQ'
    - 'Ventricles'
    - 'Hippocampus'
    - 'WholeBrain'
    - 'Entorhinal'
    - 'Fusiform'
    - 'MidTemp'
    - 'ICV'
  clinical_categorical_features: 
    - 'PTGENDER'
    - 'PTRACCAT'
    - 'PTETHCAT'
    - 'PTMARRY'
  cognitive_scores:
    - 'CDRSB'
    - 'ADAS11'
    - 'ADAS13'
    - 'ADASQ4'
    - 'MMSE'
    - 'RAVLT_immediate'
    - 'RAVLT_learning'
    - 'RAVLT_forgetting'
    - 'RAVLT_perc_forgetting'
    - 'FAQ'
model:
  learn_time_emb: False
  n_gen_feat: 54
  n_cli_feat: 37
  # n_cog_feat: 13
  n_cog_feat: 10
  seq_len: 3
  gen_emb_dim: 384
  cli_emb_dim: 128
  img_emb_dim: 128
  # cognitive_col: [3,4,5,6,7,8,9,10,11,12,13,14,15]
  cognitive_col: [3, 4, 5, 6, 7, 8, 9, 10, 11, 15]
  clinical_col: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36]
  clinical_cols:
    - 'AGE'
    - 'PTEDUCAT'
    - 'APOE4'
    - 'CDRSB'
    - 'ADAS11'
    - 'ADAS13'
    - 'ADASQ4'
    - 'MMSE'
    - 'RAVLT_immediate'
    - 'RAVLT_learning'
    - 'RAVLT_forgetting'
    - 'RAVLT_perc_forgetting'
    - 'LDELTOTAL'
    - 'DIGITSCOR'
    - 'TRABSCOR'
    - 'FAQ'
    - 'Ventricles'
    - 'Hippocampus'
    - 'WholeBrain'
    - 'Entorhinal'
    - 'Fusiform'
    - 'MidTemp'
    - 'ICV'
    - 'PTGENDER_Female'
    - 'PTGENDER_Male'
    - 'PTRACCAT_Am Indian/Alaskan'
    - 'PTRACCAT_Asian'
    - 'PTRACCAT_Black'
    - 'PTRACCAT_More than one'
    - 'PTRACCAT_White'
    - 'PTETHCAT_Hisp/Latino'
    - 'PTETHCAT_Not Hisp/Latino'
    - 'PTETHCAT_Unknown'
    - 'PTMARRY_Divorced'
    - 'PTMARRY_Married'
    - 'PTMARRY_Never married'
    - 'PTMARRY_Widowed'
  softmax_temperature: 0.07
  modality: ['clinic','image','gene']
  has_prior: False
  transformer_depth: 6
  fusion_mode: 'cross_attn'
  objective: "regression" # regression, classification
  concat_score_ratio: 1.0
  time: True